apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: fundament

# Build configuration for all images
build:
  # Local build settings - load directly into k3d (no registry needed)
  local:
    useBuildkit: true
    concurrency: 0
    push: true

  artifacts:
    - image: appstore-api
      context: .
      docker:
        dockerfile: appstore-api/Dockerfile

    - image: authn-api
      context: .
      docker:
        dockerfile: authn-api/Dockerfile

    - image: organization-api
      context: .
      docker:
        dockerfile: organization-api/Dockerfile

deploy:
  kubeContext: REQUIRES-PROFILE # kubeContext is intentionally invalid to prevent accidental deployments without a profile.
  statusCheckDeadlineSeconds: 300
  helm:
    releases:
      - name: fundament
        chartPath: charts/fundament
        namespace: fundament
        createNamespace: true
        setValueTemplates:
          imageAppstoreAPI: "{.IMAGE_FULLY_QUALIFIED_appstore_api}"
          imageAuthnAPI: "{.IMAGE_FULLY_QUALIFIED_authn_api}"
          imageOrganizationAPI: "{.IMAGE_FULLY_QUALIFIED_organization_api}"

profiles:
  - name: env-local
    deploy:
      kubeContext: k3d-fundament
    patches:
      - op: add
        path: /deploy/helm/releases/0/valuesFiles
        value:
          - charts/fundament/values-local.yaml

  - name: env-production
    deploy:
      kubeContext: PRODUCTION-NOT-AVAILABLE-YET
    patches:
      - op: add
        path: /deploy/helm/releases/0/valuesFiles
        value:
          - charts/fundament/values-production.yaml

  # Hot reload profile for local development (use with env-local: -p env-local,hotreload)
  - name: hotreload
    patches:
      - op: replace
        path: /build/artifacts/0/docker/dockerfile
        value: appstore-api/hotreload/Dockerfile
      - op: add
        path: /build/artifacts/0/sync
        value:
          manual:
            - src: appstore-api/**/*
              dest: /src
            - src: go.mod
              dest: /src
            - src: go.sum
              dest: /src
      - op: replace
        path: /build/artifacts/1/docker/dockerfile
        value: authn-api/hotreload/Dockerfile
      - op: add
        path: /build/artifacts/1/sync
        value:
          manual:
            - src: authn-api/**/*
              dest: /src
            - src: go.mod
              dest: /src
            - src: go.sum
              dest: /src
      - op: replace
        path: /build/artifacts/2/docker/dockerfile
        value: organization-api/hotreload/Dockerfile
      - op: add
        path: /build/artifacts/2/sync
        value:
          manual:
            - src: organization-api/**/*
              dest: /src
            - src: go.mod
              dest: /src
            - src: go.sum
              dest: /src
