apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: fundament

# Build configuration for all images
build:
  # Local build settings - load directly into k3d (no registry needed)
  local:
    useBuildkit: true
    concurrency: 0
    push: true

  artifacts:
    - image: appstore-api
      context: .
      ko:
        main: ./appstore-api
        dependencies:
          paths: ["go.mod", "appstore-api/**/*.go"]

    - image: authn-api
      context: .
      ko:
        main: ./authn-api
        dependencies:
          paths: ["go.mod", "authn-api/**/*.go"]

    - image: organization-api
      context: .
      ko:
        main: ./organization-api
        dependencies:
          paths: ["go.mod", "organization-api/**/*.go"]

deploy:
  kubeContext: REQUIRES-PROFILE # kubeContext is intentionally invalid to prevent accidental deployments without a profile.
  statusCheckDeadlineSeconds: 300
  helm:
    releases:
      - name: fundament
        chartPath: charts/fundament
        namespace: fundament
        createNamespace: true
        setValueTemplates:
          imageAppstoreAPI: "{.IMAGE_FULLY_QUALIFIED_appstore_api}"
          imageAuthnAPI: "{.IMAGE_FULLY_QUALIFIED_authn_api}"
          imageOrganizationAPI: "{.IMAGE_FULLY_QUALIFIED_organization_api}"

profiles:
  - name: env-local
    deploy:
      kubeContext: k3d-fundament
    patches:
      - op: add
        path: /deploy/helm/releases/0/valuesFiles
        value:
          - charts/fundament/values-local.yaml

  - name: env-production
    deploy:
      kubeContext: PRODUCTION-NOT-AVAILABLE-YET
    patches:
      - op: add
        path: /deploy/helm/releases/0/valuesFiles
        value:
          - charts/fundament/values-production.yaml
