apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: fundament

# Build configuration for all images
build:
  # Local build settings - load directly into k3d (no registry needed)
  local:
    useBuildkit: true
    concurrency: 0
    push: true

  artifacts:
    - image: appstore-api
      context: .
      docker:
        dockerfile: appstore-api/Dockerfile

    - image: authn-api
      context: .
      docker:
        dockerfile: authn-api/Dockerfile

    - image: organization-api
      context: .
      docker:
        dockerfile: organization-api/Dockerfile

    - image: db-migrations
      context: db
      docker:
        dockerfile: Dockerfile

    - image: login-frontend
      context: login-frontend
      docker:
        dockerfile: Dockerfile
deploy:
  kubeContext: REQUIRES-PROFILE # kubeContext is intentionally invalid to prevent accidental deployments without a profile.
  statusCheckDeadlineSeconds: 300
  helm:
    releases:
      - name: fundament
        chartPath: charts/fundament
        namespace: fundament
        createNamespace: true
        setValueTemplates:
          images.dbMigrations: "{{.IMAGE_FULLY_QUALIFIED_db_migrations}}"
          images.appstoreApi: "{{.IMAGE_FULLY_QUALIFIED_appstore_api}}"
          images.authnApi: "{{.IMAGE_FULLY_QUALIFIED_authn_api}}"
          images.organizationApi: "{{.IMAGE_FULLY_QUALIFIED_organization_api}}"
          images.loginFrontend: "{{.IMAGE_FULLY_QUALIFIED_login_frontend}}"

profiles:
  - name: env-local
    deploy:
      kubeContext: k3d-fundament
    patches:
      - op: add
        path: /deploy/helm/releases/0/valuesFiles
        value:
          - charts/fundament/values-local.yaml

  - name: env-production
    deploy:
      kubeContext: PRODUCTION-NOT-AVAILABLE-YET
    patches:
      - op: add
        path: /deploy/helm/releases/0/valuesFiles
        value:
          - charts/fundament/values-production.yaml

  # Hot reload profile for local development
  - name: hotreload
    patches:
      - op: replace
        path: /build/artifacts/0/docker/dockerfile
        value: appstore-api/hotreload/Dockerfile
      - op: add
        path: /build/artifacts/0/sync
        value: {}
      - op: replace
        path: /build/artifacts/1/docker/dockerfile
        value: authn-api/hotreload/Dockerfile
      - op: add
        path: /build/artifacts/1/sync
        value: {}
      - op: replace
        path: /build/artifacts/2/docker/dockerfile
        value: organization-api/hotreload/Dockerfile
      - op: add
        path: /build/artifacts/2/sync
        value: {}
