apiVersion: v1
kind: Secret
metadata:
  name: mkcert-ca
  namespace: cert-manager
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.ca.cert | b64enc | quote }}
  tls.key: {{ .Values.ca.key | b64enc | quote }}
