{{- if .Values.certificates.serviceCA.certificatePEM -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "open-fsc-inway.fullname" . }}-service-ca-certificate
  labels:
    {{- include "open-fsc-inway.labels" . | nindent 4 }}
data:
  tls.crt: {{ .Values.certificates.serviceCA.certificatePEM | b64enc | quote }}
{{- end }}
