{{- if and (not .Values.certificates.internal.caCertificatePEMExistingSecret.name) (not .Values.global.certificates.internal.caCertificatePEMExistingSecret.name) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "open-fsc-inway.fullname" . }}-internal-ca-certificate
  labels:
    {{- include "open-fsc-inway.labels" . | nindent 4 }}
data:
  tls.crt: {{ (required "Internal CA Certificate is required" (default .Values.global.certificates.internal.caCertificatePEM .Values.certificates.internal.caCertificatePEM)) | b64enc | quote }}
  tls.key: ""
{{- end }}
