{{- if $.Values.authnApi.httproute.enabled }}
{{- if not $.Values.authnApi.httproute.parentRefs }}{{ fail "authnApi.httproute.parentRefs is required when httproute is enabled" }}{{ end }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $.Release.Name }}-authn-api
  labels:
    {{- include "fundament.labels" (dict "root" $ "name" "authn-api" "component" "gateway") | nindent 4 }}
  {{- with $.Values.authnApi.httproute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- toYaml $.Values.authnApi.httproute.parentRefs | nindent 4 }}
  hostnames:
    {{- toYaml $.Values.authnApi.httproute.hostnames | nindent 4 }}
  rules:
    - backendRefs:
        - name: authn-api
          port: 8080
{{- end }}
