{{- if $.Values.dex.httproute.enabled }}
{{- if not $.Values.dex.httproute.parentRefs }}{{ fail "dex.httproute.parentRefs is required when httproute is enabled" }}{{ end }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $.Release.Name }}-dex
  labels:
    {{- include "fundament.labels" (dict "root" $ "name" "dex" "component" "gateway") | nindent 4 }}
spec:
  parentRefs:
    {{- toYaml $.Values.dex.httproute.parentRefs | nindent 4 }}
  hostnames:
    {{- toYaml $.Values.dex.httproute.hostnames | nindent 4 }}
  rules:
    - backendRefs:
        - name: dex
          port: 5556
{{- end }}
