{{- if $.Values.marketplaceAdminFrontend.httproute.enabled }}
{{- if not $.Values.marketplaceAdminFrontend.httproute.parentRefs }}{{ fail "marketplaceAdminFrontend.httproute.parentRefs is required when httproute is enabled" }}{{ end }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $.Release.Name }}-marketplace-admin-frontend
  labels:
    {{- include "fundament.labels" (dict "root" $ "name" "marketplace-admin-frontend" "component" "gateway") | nindent 4 }}
spec:
  parentRefs:
    {{- toYaml $.Values.marketplaceAdminFrontend.httproute.parentRefs | nindent 4 }}
  hostnames:
    {{- toYaml $.Values.marketplaceAdminFrontend.httproute.hostnames | nindent 4 }}
  rules:
    - backendRefs:
        - name: marketplace-admin-frontend
          port: 80
{{- end }}
