/**
 * Fails the build on broken links.
 *
 * Validation runs on the *built output* rather than on Markdown ASTs, because
 * the docs come from several sources that share no pipeline: `.md`/`.mdx` via
 * remark, `.adoc` via Asciidoctor (see asciidoc-loader.ts, which is the
 * majority of the pages), the hand-written landing page, and the autogenerated
 * sidebar. Scanning `dist/` covers all of them, and checks the final URL --
 * i.e. after the link rewrites in scripts/sync-docs.mjs.
 *
 * Links are resolved with browser semantics against `trailingSlash: 'never'`:
 * a relative link on `/docs/developer/plugins` resolves against
 * `/docs/developer/`, not `/docs/developer/plugins/`. That is a real trap for
 * index pages, and one that is invisible in production because nginx.conf
 * falls back to `/index.html` and serves the home page with a 200.
 */
import { readdirSync, readFileSync, statSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import type { AstroIntegration, AstroIntegrationLogger } from 'astro';

export interface LinksValidatorOptions {
  /** Glob patterns of link targets to skip. Matched against the raw href and the resolved path. */
  exclude?: string[];
  /** Check that `#fragment` targets exist on the destination page. Default true. */
  checkAnchors?: boolean;
  /** Check that non-page targets (images, `/assets/*`) exist in the output. Default true. */
  checkAssets?: boolean;
  /** Check external http(s) links over the network. Default `DOCS_CHECK_EXTERNAL=1`. */
  checkExternal?: boolean;
  /** Parallel external requests. Default 8. */
  externalConcurrency?: number;
  /** Extra response statuses to accept, on top of 2xx/3xx and {@link AUTH_STATUSES}. */
  externalOkStatuses?: number[];
  /** Report findings without failing the build. Default false. */
  warnOnly?: boolean;
}

interface Finding {
  /** Repo-relative source file, or the route when it cannot be resolved. */
  source: string;
  route: string;
  href: string;
  reason: string;
}

interface Page {
  route: string;
  ids: Set<string>;
  links: { href: string; kind: 'page' | 'asset' }[];
}

/**
 * A page behind a login middleware answers with an auth challenge rather than
 * its content. The check asks "does this URL exist", so a challenge counts as
 * existing -- only the body is gated. 405 covers hosts that reject HEAD, 429 a
 * rate limiter that never got as far as routing the request.
 */
const AUTH_STATUSES = [401, 403, 405, 429];

const NON_HTTP_SCHEME = /^[a-z][a-z0-9+.-]*:/i;
const EXTERNAL_HREF = /^(?:[a-z][a-z0-9+.-]*:)?\/\//i;
const ANCHOR_HREF = /<a\b[^>]*?\shref=(["'])(.*?)\1/gis;
const IMG_SRC = /<img\b[^>]*?\ssrc=(["'])(.*?)\1/gis;
const ELEMENT_ID = /\sid=(["'])(.*?)\1/gis;
const ANCHOR_NAME = /<a\b[^>]*?\sname=(["'])(.*?)\1/gis;

/** `**` spans separators, `*` does not. Everything else is literal. */
function globToRegExp(pattern: string): RegExp {
  const source = pattern
    .split('**')
    .map((part) =>
      part
        .split('*')
        .map((literal) => literal.replace(/[.+?^${}()|[\]\\]/g, '\\$&'))
        .join('[^/]*')
    )
    .join('.*');
  return new RegExp(`^${source}$`);
}

/** Every file under `root`, as a `/`-separated path relative to it. */
function listFiles(root: string): string[] {
  return readdirSync(root, { recursive: true, withFileTypes: true })
    .filter((entry) => entry.isFile())
    .map((entry) =>
      path.relative(root, path.join(entry.parentPath, entry.name)).split(path.sep).join('/')
    );
}

/** No trailing slash, matching `trailingSlash: 'never'`. */
function normalizeRoute(route: string): string {
  const trimmed = route.replace(/\/+$/, '');
  return trimmed === '' ? '/' : trimmed;
}

/** `foo/index.html` -> `/foo`, `foo.html` -> `/foo`, `index.html` -> `/`. */
function routeFromHtmlFile(file: string): string {
  const withoutExtension = file.replace(/\.html$/, '');
  return normalizeRoute(`/${withoutExtension.replace(/(^|\/)index$/, '$1')}`);
}

function collectMatches(html: string, pattern: RegExp): string[] {
  return [...html.matchAll(pattern)].map((match) => match[2] ?? '');
}

function readPage(root: string, file: string): Page {
  const html = readFileSync(path.join(root, file), 'utf8');
  return {
    route: routeFromHtmlFile(file),
    ids: new Set([...collectMatches(html, ELEMENT_ID), ...collectMatches(html, ANCHOR_NAME)]),
    links: [
      ...collectMatches(html, ANCHOR_HREF).map((href) => ({ href, kind: 'page' as const })),
      ...collectMatches(html, IMG_SRC).map((href) => ({ href, kind: 'asset' as const })),
    ],
  };
}

/**
 * Route -> repo-relative source file, so findings point at the file an author
 * edits rather than at a path in `dist/`. Reverses the copy mapping in
 * scripts/sync-docs.mjs. Keyed lowercase: asciidoc-loader.ts lowercases slugs.
 */
function buildSourceIndex(projectRoot: string): Map<string, string> {
  const contentRoot = path.join(projectRoot, 'src/content/docs');
  const index = new Map<string, string>();
  if (!statSync(contentRoot, { throwIfNoEntry: false })?.isDirectory()) return index;

  for (const file of listFiles(contentRoot)) {
    if (!/\.(md|mdx|adoc)$/.test(file)) continue;
    const route = routeFromHtmlFile(file.replace(/\.(md|mdx|adoc)$/, '.html'));
    // src/content/docs/{docs,adr,funs}/... all come from the repo's docs/ tree.
    const repoPath = /^(docs|adr|funs)\//.test(file)
      ? path.posix.join('docs', file.replace(/^docs\//, ''))
      : path.posix.join('docs-frontend/src/content/docs', file);
    index.set(route.toLowerCase(), repoPath);
  }
  return index;
}

async function checkExternalLinks(
  urls: string[],
  concurrency: number,
  okStatuses: Set<number>,
  logger: AstroIntegrationLogger
): Promise<Map<string, string>> {
  const failures = new Map<string, string>();
  const queue = [...urls];
  logger.info(`checking ${urls.length} external links`);

  const request = async (url: string, method: 'HEAD' | 'GET') =>
    fetch(url, { method, redirect: 'follow', signal: AbortSignal.timeout(15_000) });

  const worker = async () => {
    for (let url = queue.pop(); url !== undefined; url = queue.pop()) {
      try {
        let response = await request(url, 'HEAD');
        if (!response.ok && !okStatuses.has(response.status)) {
          // Some hosts route HEAD differently than GET; confirm before failing.
          response = await request(url, 'GET');
        }
        if (!response.ok && !okStatuses.has(response.status)) {
          failures.set(url, `HTTP ${response.status}`);
        }
      } catch (error) {
        failures.set(url, error instanceof Error ? error.message : String(error));
      }
    }
  };

  await Promise.all(Array.from({ length: Math.min(concurrency, queue.length) }, worker));
  return failures;
}

export default function linksValidator(options: LinksValidatorOptions = {}): AstroIntegration {
  const {
    exclude = [],
    checkAnchors = true,
    checkAssets = true,
    checkExternal = process.env.DOCS_CHECK_EXTERNAL === '1',
    externalConcurrency = 8,
    externalOkStatuses = [],
    warnOnly = false,
  } = options;

  const excluded = exclude.map(globToRegExp);
  const isExcluded = (...candidates: string[]) =>
    candidates.some((candidate) => excluded.some((pattern) => pattern.test(candidate)));

  return {
    name: 'links-validator',
    hooks: {
      // Without the sync, src/content/docs/docs does not exist and only the
      // landing page builds — every link it makes into the docs then reports as
      // broken. Fail up front with the actual cause instead.
      'astro:config:setup': ({ config }) => {
        const synced = fileURLToPath(new URL('src/content/docs/docs', config.root));
        if (!statSync(synced, { throwIfNoEntry: false })?.isDirectory()) {
          throw new Error(
            'docs have not been synced: src/content/docs/docs is missing.\n' +
              'Run `just docs-dev` / `just docs-build`, or `node scripts/sync-docs.mjs` directly.'
          );
        }
      },

      'astro:build:done': async ({ dir, logger }) => {
        const root = fileURLToPath(dir);
        const files = listFiles(root);
        const assets = new Set(files.map((file) => `/${file}`));
        const pages = files
          .filter((file) => file.endsWith('.html'))
          .map((file) => readPage(root, file));
        const routes = new Map(pages.map((page) => [page.route, page]));
        const sources = buildSourceIndex(path.resolve(root, '..'));

        const findings: Finding[] = [];
        const externalUrls = new Map<string, Finding[]>();

        for (const page of pages) {
          const sourceFile = sources.get(page.route.toLowerCase()) ?? page.route;
          const report = (href: string, reason: string) =>
            findings.push({ source: sourceFile, route: page.route, href, reason });

          for (const { href, kind } of page.links) {
            if (href === '' || href.startsWith('?') || isExcluded(href)) continue;

            if (EXTERNAL_HREF.test(href)) {
              if (!checkExternal || !/^https?:/i.test(href)) continue;
              const url = href.split('#')[0]!;
              const pending = externalUrls.get(url) ?? [];
              pending.push({ source: sourceFile, route: page.route, href, reason: '' });
              externalUrls.set(url, pending);
              continue;
            }
            // mailto:, tel:, javascript:, data: -- nothing to resolve.
            if (NON_HTTP_SCHEME.test(href)) continue;

            // Resolving against the extensionless route (no trailing slash) is
            // exactly what a browser does under `trailingSlash: 'never'`.
            const target = new URL(href, `https://docs.invalid${page.route}`);
            const targetPath = normalizeRoute(decodeURIComponent(target.pathname));
            const fragment = decodeURIComponent(target.hash.slice(1));

            if (isExcluded(targetPath, `${targetPath}${target.hash}`)) continue;

            const targetPage = routes.get(targetPath);
            if (!targetPage) {
              if (assets.has(targetPath)) continue;
              // A target with a file extension is a static file, not a page.
              const isFile =
                kind === 'asset' || /\.[a-z0-9]+$/i.test(path.posix.basename(targetPath));
              if (isFile && !checkAssets) continue;
              report(href, isFile ? `no such file: ${targetPath}` : `no such page: ${targetPath}`);
              continue;
            }
            if (checkAnchors && fragment !== '' && !targetPage.ids.has(fragment)) {
              report(href, `no such anchor on ${targetPath}: #${fragment}`);
            }
          }
        }

        if (externalUrls.size > 0) {
          const okStatuses = new Set([...AUTH_STATUSES, ...externalOkStatuses]);
          const failures = await checkExternalLinks(
            [...externalUrls.keys()],
            externalConcurrency,
            okStatuses,
            logger
          );
          for (const [url, reason] of failures) {
            for (const finding of externalUrls.get(url) ?? []) {
              findings.push({ ...finding, reason: `unreachable: ${reason}` });
            }
          }
        }

        if (findings.length === 0) {
          logger.info(`no broken links across ${pages.length} pages`);
          return;
        }

        const bySource = new Map<string, Finding[]>();
        for (const finding of findings) {
          bySource.set(finding.source, [...(bySource.get(finding.source) ?? []), finding]);
        }
        const report = [...bySource]
          .sort(([a], [b]) => a.localeCompare(b))
          .map(([source, group]) => {
            const lines = group.map(({ href, reason }) => `    ${href}\n      ${reason}`);
            return `  ${source}  (${group[0]!.route})\n${lines.join('\n')}`;
          })
          .join('\n');
        const summary = `${findings.length} broken link(s) in ${bySource.size} page(s):\n${report}`;

        if (warnOnly) logger.warn(summary);
        else throw new Error(summary);
      },
    },
  };
}
