// AUTO-GENERATED by scripts/generate-plugin-icons.ts — run `just generate` to update.
import {
} from '@ng-icons/tabler-icons';

const pluginIcons: Record<string, string> = {
};

export default pluginIcons;
