// AUTO-GENERATED by scripts/generate-plugin-icons.ts — run `just generate` to update.
import {
  tablerApps,
  tablerCertificate,
  tablerCloudUpload,
  tablerDatabase,
  tablerRefresh,
  tablerShieldCheck,
  tablerUserCircle,
} from '@ng-icons/tabler-icons';

const pluginIcons: Record<string, string> = {
  tablerApps,
  tablerCertificate,
  tablerCloudUpload,
  tablerDatabase,
  tablerRefresh,
  tablerShieldCheck,
  tablerUserCircle,
};

export default pluginIcons;
