{{- if and (not .Values.certificates.group.caCertificatePEMExistingSecret.name) (not .Values.global.certificates.group.caCertificatePEMExistingSecret.name ) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "open-fsc-outway.fullname" . }}-group-ca-certificate
  labels:
    {{- include "open-fsc-outway.labels" . | nindent 4 }}
data:
  tls.crt: {{ (required "Group CA Certificate is required" (default .Values.global.certificates.group.caCertificatePEM .Values.certificates.group.caCertificatePEM)) | b64enc | quote }}
{{- end }}
