apiVersion: v1
kind: Service
metadata:
  name: {{ include "open-fsc-outway.fullname" . }}
  labels:
    {{- include "open-fsc-outway.labels" . | nindent 4 }}
  annotations: {{ .Values.service.annotations | toJson }}
spec:
  selector:
    {{- include "open-fsc-outway.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  ports:
  {{- if .Values.https.enabled }}
    - name: https
      port: {{ .Values.service.httpsPort }}
      targetPort: https
      protocol: TCP
  {{- else }}
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
  {{- end }}
