FROM golang:1.26.6-alpine AS builder
WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download
COPY marketplace-api/ ./marketplace-api/
COPY common/ ./common/
RUN CGO_ENABLED=0 go build -o /build/bin/marketplace-registry-api ./marketplace-api/cmd/fun-marketplace-registry-api

FROM scratch
COPY --from=builder /build/bin/marketplace-registry-api /
ENTRYPOINT ["/marketplace-registry-api"]
