// Code generated by go generate; DO NOT EDIT.
package authz

import "github.com/google/uuid"

// ObjectType identifies the type of an object (subject or resource).
type ObjectType string

const (
	ObjectTypeUser         ObjectType = "user"
	ObjectTypeOrganization ObjectType = "organization"
	ObjectTypeProject      ObjectType = "project"
)

// ActionName identifies the operation being performed.
// These map directly to OpenFGA relations.
type ActionName string

const (
	ActionMember           ActionName = "member"
	ActionAdmin            ActionName = "admin"
	ActionViewer           ActionName = "viewer"
	ActionOrganization     ActionName = "organization"
	ActionCanView          ActionName = "can_view"
	ActionCanEdit          ActionName = "can_edit"
	ActionCanDelete        ActionName = "can_delete"
	ActionCanManageMembers ActionName = "can_manage_members"
)

// Object represents an entity in an authorization check (subject or resource).
type Object struct {
	Type       ObjectType
	ID         string
	Properties map[string]any
}

// Action represents the operation being performed.
type Action struct {
	Name       ActionName
	Properties map[string]any
}

// Context provides additional environmental attributes for the evaluation.
type Context map[string]any

// EvaluationRequest represents a single access evaluation request.
type EvaluationRequest struct {
	Subject  Object
	Resource Object
	Action   Action
	Context  Context
}

// Decision represents the result of an access evaluation.
type Decision struct {
	Decision bool
	Context  Context
}

// EvaluationSemantic defines how batch evaluations are processed.
type EvaluationSemantic string

const (
	// ExecuteAll processes all requests independently (default).
	ExecuteAll EvaluationSemantic = "execute_all"
	// DenyOnFirstDeny stops processing on the first denied request.
	DenyOnFirstDeny EvaluationSemantic = "deny_on_first_deny"
	// PermitOnFirstPermit stops processing on the first permitted request.
	PermitOnFirstPermit EvaluationSemantic = "permit_on_first_permit"
)

// EvaluationsOptions configures batch evaluation behavior.
type EvaluationsOptions struct {
	Semantic EvaluationSemantic
}

// EvaluationsRequest represents a batch of access evaluation requests.
type EvaluationsRequest struct {
	// Default values applied to all evaluations
	Subject  *Object
	Resource *Object
	Action   *Action
	Context  Context

	// Individual evaluations (override defaults)
	Evaluations []EvaluationRequest
	Options     *EvaluationsOptions
}

// EvaluationsResponse contains the results of batch evaluations.
type EvaluationsResponse struct {
	Evaluations []Decision
}

// Object constructors

// User creates an Object of type user.
func User(id uuid.UUID) Object {
	return Object{
		Type: ObjectTypeUser,
		ID:   id.String(),
	}
}

// Organization creates an Object of type organization.
func Organization(id uuid.UUID) Object {
	return Object{
		Type: ObjectTypeOrganization,
		ID:   id.String(),
	}
}

// Project creates an Object of type project.
func Project(id uuid.UUID) Object {
	return Object{
		Type: ObjectTypeProject,
		ID:   id.String(),
	}
}

// Action constructors

// Member creates an Action for the member relation.
func Member() Action {
	return Action{Name: ActionMember}
}

// Admin creates an Action for the admin relation.
func Admin() Action {
	return Action{Name: ActionAdmin}
}

// Viewer creates an Action for the viewer relation.
func Viewer() Action {
	return Action{Name: ActionViewer}
}

// OrganizationAction creates an Action for the organization relation.
func OrganizationAction() Action {
	return Action{Name: ActionOrganization}
}

// CanView creates an Action for the can_view relation.
func CanView() Action {
	return Action{Name: ActionCanView}
}

// CanEdit creates an Action for the can_edit relation.
func CanEdit() Action {
	return Action{Name: ActionCanEdit}
}

// CanDelete creates an Action for the can_delete relation.
func CanDelete() Action {
	return Action{Name: ActionCanDelete}
}

// CanManageMembers creates an Action for the can_manage_members relation.
func CanManageMembers() Action {
	return Action{Name: ActionCanManageMembers}
}
