// Code generated by go generate; DO NOT EDIT.
package authz

import "github.com/google/uuid"

// ObjectType identifies the type of an object (subject or resource).
type ObjectType string

const (
	ObjectTypeUser          ObjectType = "user"
	ObjectTypeOrganization  ObjectType = "organization"
	ObjectTypeProject       ObjectType = "project"
	ObjectTypeProjectMember ObjectType = "project_member"
	ObjectTypeCluster       ObjectType = "cluster"
	ObjectTypeNodePool      ObjectType = "node_pool"
	ObjectTypeNamespace     ObjectType = "namespace"
	ObjectTypeApiKey        ObjectType = "api_key"
	ObjectTypeInstall       ObjectType = "install"
)

// ActionName identifies the operation being performed.
// These map directly to OpenFGA relations.
type ActionName string

const (
	ActionAdmin                ActionName = "admin"
	ActionViewer               ActionName = "viewer"
	ActionCanView              ActionName = "can_view"
	ActionCanEdit              ActionName = "can_edit"
	ActionCanCreateApikey      ActionName = "can_create_apikey"
	ActionCanListApikeys       ActionName = "can_list_apikeys"
	ActionCanCreateCluster     ActionName = "can_create_cluster"
	ActionCanViewCluster       ActionName = "can_view_cluster"
	ActionCanEditCluster       ActionName = "can_edit_cluster"
	ActionCanListClusters      ActionName = "can_list_clusters"
	ActionCanInviteMember      ActionName = "can_invite_member"
	ActionCanEditMember        ActionName = "can_edit_member"
	ActionCanDeleteMember      ActionName = "can_delete_member"
	ActionCanListMembers       ActionName = "can_list_members"
	ActionParent               ActionName = "parent"
	ActionProjectAdmin         ActionName = "project_admin"
	ActionProjectViewer        ActionName = "project_viewer"
	ActionCanDelete            ActionName = "can_delete"
	ActionCanManageMembers     ActionName = "can_manage_members"
	ActionCanCreateNamespace   ActionName = "can_create_namespace"
	ActionCanViewNamespace     ActionName = "can_view_namespace"
	ActionCanEditNamespace     ActionName = "can_edit_namespace"
	ActionCanListNamespaces    ActionName = "can_list_namespaces"
	ActionCanViewProjectMember ActionName = "can_view_project_member"
	ActionCanEditProjectMember ActionName = "can_edit_project_member"
	ActionOwner                ActionName = "owner"
	ActionCanCreateNodePool    ActionName = "can_create_node_pool"
	ActionCanViewNodePool      ActionName = "can_view_node_pool"
	ActionCanEditNodePool      ActionName = "can_edit_node_pool"
	ActionCanListNodePools     ActionName = "can_list_node_pools"
	ActionCanCreateInstall     ActionName = "can_create_install"
	ActionCanViewInstall       ActionName = "can_view_install"
	ActionCanEditInstall       ActionName = "can_edit_install"
	ActionCanListInstalls      ActionName = "can_list_installs"
	ActionCanCreateProject     ActionName = "can_create_project"
	ActionCanViewProject       ActionName = "can_view_project"
	ActionCanEditProject       ActionName = "can_edit_project"
	ActionCanListProjects      ActionName = "can_list_projects"
	ActionCreator              ActionName = "creator"
	ActionCanUse               ActionName = "can_use"
)

// Object represents an entity in an authorization check (subject or resource).
type Object struct {
	Type       ObjectType
	ID         string
	Properties map[string]any
}

// String formats the object as "type:id" for use in OpenFGA tuples.
func (o Object) String() string {
	return string(o.Type) + ":" + o.ID
}

// Action represents the operation being performed.
type Action struct {
	Name       ActionName
	Properties map[string]any
}

// Context provides additional environmental attributes for the evaluation.
type Context map[string]any

// EvaluationRequest represents a single access evaluation request.
type EvaluationRequest struct {
	Subject  Object
	Resource Object
	Action   Action
	Context  Context
}

// Decision represents the result of an access evaluation.
type Decision struct {
	Decision bool
	Context  Context
}

// EvaluationSemantic defines how batch evaluations are processed.
type EvaluationSemantic string

const (
	// ExecuteAll processes all requests independently (default).
	ExecuteAll EvaluationSemantic = "execute_all"
	// DenyOnFirstDeny stops processing on the first denied request.
	DenyOnFirstDeny EvaluationSemantic = "deny_on_first_deny"
	// PermitOnFirstPermit stops processing on the first permitted request.
	PermitOnFirstPermit EvaluationSemantic = "permit_on_first_permit"
)

// EvaluationsOptions configures batch evaluation behavior.
type EvaluationsOptions struct {
	Semantic EvaluationSemantic
}

// EvaluationsRequest represents a batch of access evaluation requests.
type EvaluationsRequest struct {
	// Default values applied to all evaluations
	Subject  *Object
	Resource *Object
	Action   *Action
	Context  Context

	// Individual evaluations (override defaults)
	Evaluations []EvaluationRequest
	Options     *EvaluationsOptions
}

// EvaluationsResponse contains the results of batch evaluations.
type EvaluationsResponse struct {
	Evaluations []Decision
}

// Object constructors

// User creates an Object of type user.
func User(id uuid.UUID) Object {
	return Object{
		Type: ObjectTypeUser,
		ID:   id.String(),
	}
}

// Organization creates an Object of type organization.
func Organization(id uuid.UUID) Object {
	return Object{
		Type: ObjectTypeOrganization,
		ID:   id.String(),
	}
}

// Project creates an Object of type project.
func Project(id uuid.UUID) Object {
	return Object{
		Type: ObjectTypeProject,
		ID:   id.String(),
	}
}

// ProjectMember creates an Object of type project_member.
func ProjectMember(id uuid.UUID) Object {
	return Object{
		Type: ObjectTypeProjectMember,
		ID:   id.String(),
	}
}

// Cluster creates an Object of type cluster.
func Cluster(id uuid.UUID) Object {
	return Object{
		Type: ObjectTypeCluster,
		ID:   id.String(),
	}
}

// NodePool creates an Object of type node_pool.
func NodePool(id uuid.UUID) Object {
	return Object{
		Type: ObjectTypeNodePool,
		ID:   id.String(),
	}
}

// Namespace creates an Object of type namespace.
func Namespace(id uuid.UUID) Object {
	return Object{
		Type: ObjectTypeNamespace,
		ID:   id.String(),
	}
}

// ApiKey creates an Object of type api_key.
func ApiKey(id uuid.UUID) Object {
	return Object{
		Type: ObjectTypeApiKey,
		ID:   id.String(),
	}
}

// Install creates an Object of type install.
func Install(id uuid.UUID) Object {
	return Object{
		Type: ObjectTypeInstall,
		ID:   id.String(),
	}
}

// Action constructors

// Admin creates an Action for the admin relation.
func Admin() Action {
	return Action{Name: ActionAdmin}
}

// Viewer creates an Action for the viewer relation.
func Viewer() Action {
	return Action{Name: ActionViewer}
}

// CanView creates an Action for the can_view relation.
func CanView() Action {
	return Action{Name: ActionCanView}
}

// CanEdit creates an Action for the can_edit relation.
func CanEdit() Action {
	return Action{Name: ActionCanEdit}
}

// CanCreateApikey creates an Action for the can_create_apikey relation.
func CanCreateApikey() Action {
	return Action{Name: ActionCanCreateApikey}
}

// CanListApikeys creates an Action for the can_list_apikeys relation.
func CanListApikeys() Action {
	return Action{Name: ActionCanListApikeys}
}

// CanCreateCluster creates an Action for the can_create_cluster relation.
func CanCreateCluster() Action {
	return Action{Name: ActionCanCreateCluster}
}

// CanViewCluster creates an Action for the can_view_cluster relation.
func CanViewCluster() Action {
	return Action{Name: ActionCanViewCluster}
}

// CanEditCluster creates an Action for the can_edit_cluster relation.
func CanEditCluster() Action {
	return Action{Name: ActionCanEditCluster}
}

// CanListClusters creates an Action for the can_list_clusters relation.
func CanListClusters() Action {
	return Action{Name: ActionCanListClusters}
}

// CanInviteMember creates an Action for the can_invite_member relation.
func CanInviteMember() Action {
	return Action{Name: ActionCanInviteMember}
}

// CanEditMember creates an Action for the can_edit_member relation.
func CanEditMember() Action {
	return Action{Name: ActionCanEditMember}
}

// CanDeleteMember creates an Action for the can_delete_member relation.
func CanDeleteMember() Action {
	return Action{Name: ActionCanDeleteMember}
}

// CanListMembers creates an Action for the can_list_members relation.
func CanListMembers() Action {
	return Action{Name: ActionCanListMembers}
}

// Parent creates an Action for the parent relation.
func Parent() Action {
	return Action{Name: ActionParent}
}

// ProjectAdmin creates an Action for the project_admin relation.
func ProjectAdmin() Action {
	return Action{Name: ActionProjectAdmin}
}

// ProjectViewer creates an Action for the project_viewer relation.
func ProjectViewer() Action {
	return Action{Name: ActionProjectViewer}
}

// CanDelete creates an Action for the can_delete relation.
func CanDelete() Action {
	return Action{Name: ActionCanDelete}
}

// CanManageMembers creates an Action for the can_manage_members relation.
func CanManageMembers() Action {
	return Action{Name: ActionCanManageMembers}
}

// CanCreateNamespace creates an Action for the can_create_namespace relation.
func CanCreateNamespace() Action {
	return Action{Name: ActionCanCreateNamespace}
}

// CanViewNamespace creates an Action for the can_view_namespace relation.
func CanViewNamespace() Action {
	return Action{Name: ActionCanViewNamespace}
}

// CanEditNamespace creates an Action for the can_edit_namespace relation.
func CanEditNamespace() Action {
	return Action{Name: ActionCanEditNamespace}
}

// CanListNamespaces creates an Action for the can_list_namespaces relation.
func CanListNamespaces() Action {
	return Action{Name: ActionCanListNamespaces}
}

// CanViewProjectMember creates an Action for the can_view_project_member relation.
func CanViewProjectMember() Action {
	return Action{Name: ActionCanViewProjectMember}
}

// CanEditProjectMember creates an Action for the can_edit_project_member relation.
func CanEditProjectMember() Action {
	return Action{Name: ActionCanEditProjectMember}
}

// Owner creates an Action for the owner relation.
func Owner() Action {
	return Action{Name: ActionOwner}
}

// CanCreateNodePool creates an Action for the can_create_node_pool relation.
func CanCreateNodePool() Action {
	return Action{Name: ActionCanCreateNodePool}
}

// CanViewNodePool creates an Action for the can_view_node_pool relation.
func CanViewNodePool() Action {
	return Action{Name: ActionCanViewNodePool}
}

// CanEditNodePool creates an Action for the can_edit_node_pool relation.
func CanEditNodePool() Action {
	return Action{Name: ActionCanEditNodePool}
}

// CanListNodePools creates an Action for the can_list_node_pools relation.
func CanListNodePools() Action {
	return Action{Name: ActionCanListNodePools}
}

// CanCreateInstall creates an Action for the can_create_install relation.
func CanCreateInstall() Action {
	return Action{Name: ActionCanCreateInstall}
}

// CanViewInstall creates an Action for the can_view_install relation.
func CanViewInstall() Action {
	return Action{Name: ActionCanViewInstall}
}

// CanEditInstall creates an Action for the can_edit_install relation.
func CanEditInstall() Action {
	return Action{Name: ActionCanEditInstall}
}

// CanListInstalls creates an Action for the can_list_installs relation.
func CanListInstalls() Action {
	return Action{Name: ActionCanListInstalls}
}

// CanCreateProject creates an Action for the can_create_project relation.
func CanCreateProject() Action {
	return Action{Name: ActionCanCreateProject}
}

// CanViewProject creates an Action for the can_view_project relation.
func CanViewProject() Action {
	return Action{Name: ActionCanViewProject}
}

// CanEditProject creates an Action for the can_edit_project relation.
func CanEditProject() Action {
	return Action{Name: ActionCanEditProject}
}

// CanListProjects creates an Action for the can_list_projects relation.
func CanListProjects() Action {
	return Action{Name: ActionCanListProjects}
}

// Creator creates an Action for the creator relation.
func Creator() Action {
	return Action{Name: ActionCreator}
}

// CanUse creates an Action for the can_use relation.
func CanUse() Action {
	return Action{Name: ActionCanUse}
}
