// Code generated by _generate-dbconstraints. DO NOT EDIT.

package dbconst

const (
	// ConstraintApiKeysFkOrganization is defined on authn.api_keys.
	ConstraintApiKeysFkOrganization = "api_keys_fk_organization"
	// ConstraintApiKeysFkUser is defined on authn.api_keys.
	ConstraintApiKeysFkUser = "api_keys_fk_user"
	// ConstraintApiKeysUqName is defined on authn.api_keys.
	ConstraintApiKeysUqName = "api_keys_uq_name"
	// ConstraintApiKeysUqTokenHash is defined on authn.api_keys.
	ConstraintApiKeysUqTokenHash = "api_keys_uq_token_hash"
	// ConstraintCategoriesUqName is defined on zappstore.categories.
	ConstraintCategoriesUqName = "categories_uq_name"
	// ConstraintClustersCkStatus is defined on tenant.clusters.
	ConstraintClustersCkStatus = "clusters_ck_status"
	// ConstraintClustersFkOrganization is defined on tenant.clusters.
	ConstraintClustersFkOrganization = "clusters_fk_organization"
	// ConstraintClustersUqName is defined on tenant.clusters.
	ConstraintClustersUqName = "clusters_uq_name"
	// ConstraintInstallsFkCluster is defined on zappstore.installs.
	ConstraintInstallsFkCluster = "installs_fk_cluster"
	// ConstraintInstallsFkPlugin is defined on zappstore.installs.
	ConstraintInstallsFkPlugin = "installs_fk_plugin"
	// ConstraintInstallsUq is defined on zappstore.installs.
	ConstraintInstallsUq = "installs_uq"
	// ConstraintNamespacesCkName is defined on tenant.namespaces.
	ConstraintNamespacesCkName = "namespaces_ck_name"
	// ConstraintNamespacesFkCluster is defined on tenant.namespaces.
	ConstraintNamespacesFkCluster = "namespaces_fk_cluster"
	// ConstraintNamespacesFkProject is defined on tenant.namespaces.
	ConstraintNamespacesFkProject = "namespaces_fk_project"
	// ConstraintNamespacesUqName is defined on tenant.namespaces.
	ConstraintNamespacesUqName = "namespaces_uq_name"
	// ConstraintNodePoolsFkCluster is defined on tenant.node_pools.
	ConstraintNodePoolsFkCluster = "node_pools_fk_cluster"
	// ConstraintNodePoolsUqName is defined on tenant.node_pools.
	ConstraintNodePoolsUqName = "node_pools_uq_name"
	// ConstraintOrganizationsUqName is defined on tenant.organizations.
	ConstraintOrganizationsUqName = "organizations_uq_name"
	// ConstraintPluginDocumentationLinksFkPlugin is defined on zappstore.plugin_documentation_links.
	ConstraintPluginDocumentationLinksFkPlugin = "plugin_documentation_links_fk_plugin"
	// ConstraintPluginsCategoriesCategoryId is defined on zappstore.categories_plugins.
	ConstraintPluginsCategoriesCategoryId = "plugins_categories_category_id"
	// ConstraintPluginsCategoriesPluginId is defined on zappstore.categories_plugins.
	ConstraintPluginsCategoriesPluginId = "plugins_categories_plugin_id"
	// ConstraintPluginsPresetsPluginId is defined on zappstore.preset_plugins.
	ConstraintPluginsPresetsPluginId = "plugins_presets_plugin_id"
	// ConstraintPluginsPresetsPresetId is defined on zappstore.preset_plugins.
	ConstraintPluginsPresetsPresetId = "plugins_presets_preset_id"
	// ConstraintPluginsTagsPluginId is defined on zappstore.plugins_tags.
	ConstraintPluginsTagsPluginId = "plugins_tags_plugin_id"
	// ConstraintPluginsTagsTagId is defined on zappstore.plugins_tags.
	ConstraintPluginsTagsTagId = "plugins_tags_tag_id"
	// ConstraintPluginsUqName is defined on zappstore.plugins.
	ConstraintPluginsUqName = "plugins_uq_name"
	// ConstraintPresetsUqName is defined on zappstore.presets.
	ConstraintPresetsUqName = "presets_uq_name"
	// ConstraintProjectMembersCkRole is defined on tenant.project_members.
	ConstraintProjectMembersCkRole = "project_members_ck_role"
	// ConstraintProjectMembersFkProject is defined on tenant.project_members.
	ConstraintProjectMembersFkProject = "project_members_fk_project"
	// ConstraintProjectMembersFkUser is defined on tenant.project_members.
	ConstraintProjectMembersFkUser = "project_members_fk_user"
	// ConstraintProjectMembersUqProjectUser is defined on tenant.project_members.
	ConstraintProjectMembersUqProjectUser = "project_members_uq_project_user"
	// ConstraintProjectsFkOrganization is defined on tenant.projects.
	ConstraintProjectsFkOrganization = "projects_fk_organization"
	// ConstraintProjectsUqOrganizationName is defined on tenant.projects.
	ConstraintProjectsUqOrganizationName = "projects_uq_organization_name"
	// ConstraintRequireAdmin is defined on (constraint trigger).
	ConstraintRequireAdmin = "require_admin"
	// ConstraintTagsUqName is defined on zappstore.tags.
	ConstraintTagsUqName = "tags_uq_name"
	// ConstraintUsersFkOrganization is defined on tenant.users.
	ConstraintUsersFkOrganization = "users_fk_organization"
	// ConstraintUsersUqExternalId is defined on tenant.users.
	ConstraintUsersUqExternalId = "users_uq_external_id"
	// ConstraintVerifyDeleted is defined on (constraint trigger).
	ConstraintVerifyDeleted = "verify_deleted"
)
