// Code generated by _generate-dbconst-enums. DO NOT EDIT.

package dbconst

// ClusterStatus represents valid values for tenant.clusters.status.
type ClusterStatus string

const (
	ClusterStatus_Unspecified ClusterStatus = "unspecified"
	ClusterStatus_Provisioning ClusterStatus = "provisioning"
	ClusterStatus_Starting ClusterStatus = "starting"
	ClusterStatus_Running ClusterStatus = "running"
	ClusterStatus_Upgrading ClusterStatus = "upgrading"
	ClusterStatus_Error ClusterStatus = "error"
	ClusterStatus_Stopping ClusterStatus = "stopping"
	ClusterStatus_Stopped ClusterStatus = "stopped"
)
