// Code generated by _generate-dbconst-enums. DO NOT EDIT.

package dbconst

// ClusterEventEventType represents valid values for tenant.cluster_events.event_type.
type ClusterEventEventType string

const (
	ClusterEventEventType_SyncRequested ClusterEventEventType = "sync_requested"
	ClusterEventEventType_SyncClaimed ClusterEventEventType = "sync_claimed"
	ClusterEventEventType_SyncSucceeded ClusterEventEventType = "sync_succeeded"
	ClusterEventEventType_SyncFailed ClusterEventEventType = "sync_failed"
	ClusterEventEventType_StatusProgressing ClusterEventEventType = "status_progressing"
	ClusterEventEventType_StatusReady ClusterEventEventType = "status_ready"
	ClusterEventEventType_StatusError ClusterEventEventType = "status_error"
	ClusterEventEventType_StatusDeleted ClusterEventEventType = "status_deleted"
)

// ClusterEventSyncAction represents valid values for tenant.cluster_events.sync_action.
type ClusterEventSyncAction string

const (
	ClusterEventSyncAction_Sync ClusterEventSyncAction = "sync"
	ClusterEventSyncAction_Delete ClusterEventSyncAction = "delete"
)

// OutboxStatus represents valid values for authz.outbox.status.
type OutboxStatus string

const (
	OutboxStatus_Pending OutboxStatus = "pending"
	OutboxStatus_Completed OutboxStatus = "completed"
	OutboxStatus_Retrying OutboxStatus = "retrying"
	OutboxStatus_Failed OutboxStatus = "failed"
)

// ProjectMemberRole represents valid values for tenant.project_members.role.
type ProjectMemberRole string

const (
	ProjectMemberRole_Admin ProjectMemberRole = "admin"
	ProjectMemberRole_Viewer ProjectMemberRole = "viewer"
)

// UserRole represents valid values for tenant.users.role.
type UserRole string

const (
	UserRole_Admin UserRole = "admin"
	UserRole_Viewer UserRole = "viewer"
)
