// Code generated by _generate-dbconst-enums. DO NOT EDIT.

package dbconst

// ClusterEventEventType represents valid values for tenant.cluster_events.event_type.
type ClusterEventEventType string

const (
	ClusterEventEventType_SyncRequested ClusterEventEventType = "sync_requested"
	ClusterEventEventType_SyncClaimed ClusterEventEventType = "sync_claimed"
	ClusterEventEventType_SyncSucceeded ClusterEventEventType = "sync_succeeded"
	ClusterEventEventType_SyncFailed ClusterEventEventType = "sync_failed"
	ClusterEventEventType_StatusProgressing ClusterEventEventType = "status_progressing"
	ClusterEventEventType_StatusReady ClusterEventEventType = "status_ready"
	ClusterEventEventType_StatusError ClusterEventEventType = "status_error"
	ClusterEventEventType_StatusDeleted ClusterEventEventType = "status_deleted"
)

// ClusterEventSyncAction represents valid values for tenant.cluster_events.sync_action.
type ClusterEventSyncAction string

const (
	ClusterEventSyncAction_Sync ClusterEventSyncAction = "sync"
	ClusterEventSyncAction_Delete ClusterEventSyncAction = "delete"
)

// ProjectMemberRole represents valid values for tenant.project_members.role.
type ProjectMemberRole string

const (
	ProjectMemberRole_Admin ProjectMemberRole = "admin"
	ProjectMemberRole_Viewer ProjectMemberRole = "viewer"
)
