// Code generated by _generate-dbconst-hints. DO NOT EDIT.

package dbconst

const (
	// HintApiKeyDeleted can be thrown by authn.api_key_get_by_hash.
	HintApiKeyDeleted = "api_key_deleted"
	// HintApiKeyExpired can be thrown by authn.api_key_get_by_hash.
	HintApiKeyExpired = "api_key_expired"
	// HintApiKeyRevoked can be thrown by authn.api_key_get_by_hash.
	HintApiKeyRevoked = "api_key_revoked"
	// HintProjectContainsOneAdmin can be thrown by tenant.project_members_tr_protect_last_admin.
	HintProjectContainsOneAdmin = "project_contains_one_admin"
)
