// Code generated by _generate-dbconst-hints. DO NOT EDIT.

package dbconst

const (
	// HintClusterDefaultsBelowProject can be thrown by tenant.clusters_tr_verify_defaults.
	HintClusterDefaultsBelowProject = "cluster_defaults_below_project"
	// HintNodePoolRegionMismatch can be thrown by tenant.node_pool_region_match_trigger.
	HintNodePoolRegionMismatch = "node_pool_region_mismatch"
	// HintProjectContainsOneAdmin can be thrown by tenant.project_members_tr_protect_last_admin.
	HintProjectContainsOneAdmin = "project_contains_one_admin"
	// HintProjectDefaultsExceedCluster can be thrown by tenant.projects_tr_verify_defaults.
	HintProjectDefaultsExceedCluster = "project_defaults_exceed_cluster"
)
