// Code generated by _generate-dbconst-hints. DO NOT EDIT.

package dbconst

const (
	// HintProjectContainsOneAdmin can be thrown by tenant.project_members_tr_protect_last_admin.
	HintProjectContainsOneAdmin = "project_contains_one_admin"
)
