// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type OrganizationCluster struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	Name     string
	Created  pgtype.Timestamptz
	Deleted  pgtype.Timestamptz
}

type OrganizationNamespace struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	ClusterID uuid.UUID
	Name      string
	Created   pgtype.Timestamptz
	Deleted   pgtype.Timestamptz
}

type OrganizationProject struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	Name     string
	Created  pgtype.Timestamptz
}

type OrganizationTenant struct {
	ID      uuid.UUID
	Name    string
	Created pgtype.Timestamptz
}

type OrganizationUser struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	Name       string
	ExternalID string
	Created    pgtype.Timestamptz
}
