//go:build go1.22

// Package authnhttp provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package authnhttp

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
	CookieAuthScopes = "cookieAuth.Scopes"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Error Error message
	Error string `json:"error"`
}

// PasswordLoginRequest defines model for PasswordLoginRequest.
type PasswordLoginRequest struct {
	// Email User's email address
	Email openapi_types.Email `json:"email"`

	// Password User's password
	Password string `json:"password"`

	// ReturnTo Optional URL to redirect to after successful login
	ReturnTo *string `json:"return_to,omitempty"`
}

// RefreshResponse defines model for RefreshResponse.
type RefreshResponse struct {
	// AccessToken New JWT access token
	AccessToken string `json:"access_token"`

	// ExpiresIn Token expiry in seconds
	ExpiresIn int    `json:"expires_in"`
	TokenType string `json:"token_type"`
}

// StatusResponse defines model for StatusResponse.
type StatusResponse struct {
	Status *string `json:"status,omitempty"`
}

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	// AccessToken JWT access token
	AccessToken string `json:"access_token"`

	// ExpiresIn Token expiry in seconds
	ExpiresIn int    `json:"expires_in"`
	TokenType string `json:"token_type"`
	User      User   `json:"user"`
}

// User defines model for User.
type User struct {
	// Groups Groups the user belongs to
	Groups []string `json:"groups"`

	// Id User ID
	Id openapi_types.UUID `json:"id"`

	// Name User's display name
	Name string `json:"name"`

	// OrganizationIds Organization ID
	OrganizationIds []openapi_types.UUID `json:"organization_ids"`
}

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorResponse

// MethodNotAllowed defines model for MethodNotAllowed.
type MethodNotAllowed = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// HandleCallbackParams defines parameters for HandleCallback.
type HandleCallbackParams struct {
	// Code Authorization code from OIDC provider
	Code string `form:"code" json:"code"`

	// State State parameter for CSRF protection
	State string `form:"state" json:"state"`

	// Error Error code from OIDC provider (if authentication failed)
	Error *string `form:"error,omitempty" json:"error,omitempty"`

	// ErrorDescription Human-readable error description
	ErrorDescription *string `form:"error_description,omitempty" json:"error_description,omitempty"`
}

// HandleLoginParams defines parameters for HandleLogin.
type HandleLoginParams struct {
	// ReturnTo URL to redirect to after successful login
	ReturnTo *string `form:"return_to,omitempty" json:"return_to,omitempty"`
}

// HandlePasswordLoginJSONRequestBody defines body for HandlePasswordLogin for application/json ContentType.
type HandlePasswordLoginJSONRequestBody = PasswordLoginRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// OIDC callback handler
	// (GET /callback)
	HandleCallback(w http.ResponseWriter, r *http.Request, params HandleCallbackParams)
	// Initiate OIDC login flow
	// (GET /login)
	HandleLogin(w http.ResponseWriter, r *http.Request, params HandleLoginParams)
	// Password-based login
	// (POST /login/password)
	HandlePasswordLogin(w http.ResponseWriter, r *http.Request)
	// Logout user
	// (POST /logout)
	HandleLogout(w http.ResponseWriter, r *http.Request)
	// Refresh JWT token
	// (POST /refresh)
	HandleRefresh(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// HandleCallback operation middleware
func (siw *ServerInterfaceWrapper) HandleCallback(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params HandleCallbackParams

	// ------------- Required query parameter "code" -------------

	if paramValue := r.URL.Query().Get("code"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "code"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "code", r.URL.Query(), &params.Code)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		return
	}

	// ------------- Required query parameter "state" -------------

	if paramValue := r.URL.Query().Get("state"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "state"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "state", r.URL.Query(), &params.State)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		return
	}

	// ------------- Optional query parameter "error" -------------

	err = runtime.BindQueryParameter("form", true, false, "error", r.URL.Query(), &params.Error)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "error", Err: err})
		return
	}

	// ------------- Optional query parameter "error_description" -------------

	err = runtime.BindQueryParameter("form", true, false, "error_description", r.URL.Query(), &params.ErrorDescription)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "error_description", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HandleCallback(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HandleLogin operation middleware
func (siw *ServerInterfaceWrapper) HandleLogin(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params HandleLoginParams

	// ------------- Optional query parameter "return_to" -------------

	err = runtime.BindQueryParameter("form", true, false, "return_to", r.URL.Query(), &params.ReturnTo)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "return_to", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HandleLogin(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HandlePasswordLogin operation middleware
func (siw *ServerInterfaceWrapper) HandlePasswordLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HandlePasswordLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HandleLogout operation middleware
func (siw *ServerInterfaceWrapper) HandleLogout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HandleLogout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HandleRefresh operation middleware
func (siw *ServerInterfaceWrapper) HandleRefresh(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HandleRefresh(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/callback", wrapper.HandleCallback)
	m.HandleFunc("GET "+options.BaseURL+"/login", wrapper.HandleLogin)
	m.HandleFunc("POST "+options.BaseURL+"/login/password", wrapper.HandlePasswordLogin)
	m.HandleFunc("POST "+options.BaseURL+"/logout", wrapper.HandleLogout)
	m.HandleFunc("POST "+options.BaseURL+"/refresh", wrapper.HandleRefresh)

	return m
}

type BadRequestJSONResponse ErrorResponse

type InternalServerErrorJSONResponse ErrorResponse

type MethodNotAllowedJSONResponse ErrorResponse

type UnauthorizedJSONResponse ErrorResponse

type HandleCallbackRequestObject struct {
	Params HandleCallbackParams
}

type HandleCallbackResponseObject interface {
	VisitHandleCallbackResponse(w http.ResponseWriter) error
}

type HandleCallback307ResponseHeaders struct {
	Location  string
	SetCookie string
}

type HandleCallback307Response struct {
	Headers HandleCallback307ResponseHeaders
}

func (response HandleCallback307Response) VisitHandleCallbackResponse(w http.ResponseWriter) error {
	w.Header().Set("Location", fmt.Sprint(response.Headers.Location))
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(307)
	return nil
}

type HandleCallback400JSONResponse struct{ BadRequestJSONResponse }

func (response HandleCallback400JSONResponse) VisitHandleCallbackResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type HandleCallback401JSONResponse struct{ UnauthorizedJSONResponse }

func (response HandleCallback401JSONResponse) VisitHandleCallbackResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type HandleCallback500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response HandleCallback500JSONResponse) VisitHandleCallbackResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type HandleLoginRequestObject struct {
	Params HandleLoginParams
}

type HandleLoginResponseObject interface {
	VisitHandleLoginResponse(w http.ResponseWriter) error
}

type HandleLogin307ResponseHeaders struct {
	Location  string
	SetCookie string
}

type HandleLogin307Response struct {
	Headers HandleLogin307ResponseHeaders
}

func (response HandleLogin307Response) VisitHandleLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Location", fmt.Sprint(response.Headers.Location))
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(307)
	return nil
}

type HandleLogin500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response HandleLogin500JSONResponse) VisitHandleLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type HandlePasswordLoginRequestObject struct {
	Body *HandlePasswordLoginJSONRequestBody
}

type HandlePasswordLoginResponseObject interface {
	VisitHandlePasswordLoginResponse(w http.ResponseWriter) error
}

type HandlePasswordLogin200ResponseHeaders struct {
	SetCookie string
}

type HandlePasswordLogin200JSONResponse struct {
	Body    TokenResponse
	Headers HandlePasswordLogin200ResponseHeaders
}

func (response HandlePasswordLogin200JSONResponse) VisitHandlePasswordLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type HandlePasswordLogin400JSONResponse struct{ BadRequestJSONResponse }

func (response HandlePasswordLogin400JSONResponse) VisitHandlePasswordLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type HandlePasswordLogin401JSONResponse struct{ UnauthorizedJSONResponse }

func (response HandlePasswordLogin401JSONResponse) VisitHandlePasswordLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type HandlePasswordLogin405JSONResponse struct{ MethodNotAllowedJSONResponse }

func (response HandlePasswordLogin405JSONResponse) VisitHandlePasswordLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(405)

	return json.NewEncoder(w).Encode(response)
}

type HandlePasswordLogin500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response HandlePasswordLogin500JSONResponse) VisitHandlePasswordLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type HandleLogoutRequestObject struct {
}

type HandleLogoutResponseObject interface {
	VisitHandleLogoutResponse(w http.ResponseWriter) error
}

type HandleLogout200ResponseHeaders struct {
	SetCookie string
}

type HandleLogout200JSONResponse struct {
	Body    StatusResponse
	Headers HandleLogout200ResponseHeaders
}

func (response HandleLogout200JSONResponse) VisitHandleLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type HandleLogout405JSONResponse struct{ MethodNotAllowedJSONResponse }

func (response HandleLogout405JSONResponse) VisitHandleLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(405)

	return json.NewEncoder(w).Encode(response)
}

type HandleRefreshRequestObject struct {
}

type HandleRefreshResponseObject interface {
	VisitHandleRefreshResponse(w http.ResponseWriter) error
}

type HandleRefresh200ResponseHeaders struct {
	SetCookie string
}

type HandleRefresh200JSONResponse struct {
	Body    RefreshResponse
	Headers HandleRefresh200ResponseHeaders
}

func (response HandleRefresh200JSONResponse) VisitHandleRefreshResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type HandleRefresh401JSONResponse struct{ UnauthorizedJSONResponse }

func (response HandleRefresh401JSONResponse) VisitHandleRefreshResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type HandleRefresh405JSONResponse struct{ MethodNotAllowedJSONResponse }

func (response HandleRefresh405JSONResponse) VisitHandleRefreshResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(405)

	return json.NewEncoder(w).Encode(response)
}

type HandleRefresh500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response HandleRefresh500JSONResponse) VisitHandleRefreshResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// OIDC callback handler
	// (GET /callback)
	HandleCallback(ctx context.Context, request HandleCallbackRequestObject) (HandleCallbackResponseObject, error)
	// Initiate OIDC login flow
	// (GET /login)
	HandleLogin(ctx context.Context, request HandleLoginRequestObject) (HandleLoginResponseObject, error)
	// Password-based login
	// (POST /login/password)
	HandlePasswordLogin(ctx context.Context, request HandlePasswordLoginRequestObject) (HandlePasswordLoginResponseObject, error)
	// Logout user
	// (POST /logout)
	HandleLogout(ctx context.Context, request HandleLogoutRequestObject) (HandleLogoutResponseObject, error)
	// Refresh JWT token
	// (POST /refresh)
	HandleRefresh(ctx context.Context, request HandleRefreshRequestObject) (HandleRefreshResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// HandleCallback operation middleware
func (sh *strictHandler) HandleCallback(w http.ResponseWriter, r *http.Request, params HandleCallbackParams) {
	var request HandleCallbackRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.HandleCallback(ctx, request.(HandleCallbackRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "HandleCallback")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HandleCallbackResponseObject); ok {
		if err := validResponse.VisitHandleCallbackResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// HandleLogin operation middleware
func (sh *strictHandler) HandleLogin(w http.ResponseWriter, r *http.Request, params HandleLoginParams) {
	var request HandleLoginRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.HandleLogin(ctx, request.(HandleLoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "HandleLogin")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HandleLoginResponseObject); ok {
		if err := validResponse.VisitHandleLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// HandlePasswordLogin operation middleware
func (sh *strictHandler) HandlePasswordLogin(w http.ResponseWriter, r *http.Request) {
	var request HandlePasswordLoginRequestObject

	var body HandlePasswordLoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.HandlePasswordLogin(ctx, request.(HandlePasswordLoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "HandlePasswordLogin")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HandlePasswordLoginResponseObject); ok {
		if err := validResponse.VisitHandlePasswordLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// HandleLogout operation middleware
func (sh *strictHandler) HandleLogout(w http.ResponseWriter, r *http.Request) {
	var request HandleLogoutRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.HandleLogout(ctx, request.(HandleLogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "HandleLogout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HandleLogoutResponseObject); ok {
		if err := validResponse.VisitHandleLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// HandleRefresh operation middleware
func (sh *strictHandler) HandleRefresh(w http.ResponseWriter, r *http.Request) {
	var request HandleRefreshRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.HandleRefresh(ctx, request.(HandleRefreshRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "HandleRefresh")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HandleRefreshResponseObject); ok {
		if err := validResponse.VisitHandleRefreshResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
