#!/usr/bin/env bun
/**
 * Reads all public/plugins/*.plugin.yaml files, collects every referenced icon
 * name (from metadata.icon and menu[].icon), and generates a TypeScript file
 * that re-exports only those icons from @ng-icons/tabler-icons.
 *
 * This lets the Angular build tree-shake everything else out of the bundle.
 * Run via: just generate
 */
import { readFileSync, writeFileSync, readdirSync } from 'fs';
import { join } from 'path';
import { load } from 'js-yaml';

const pluginsDir = join(import.meta.dirname, '../public/plugins');
const outputFile = join(
  import.meta.dirname,
  '../src/app/plugin-resources/generated-plugin-icons.ts',
);

interface RawPlugin {
  menu?: {
    organization?: { icon?: string }[];
    project?: { icon?: string }[];
  };
}

const icons = new Set<string>();

readdirSync(pluginsDir)
  .filter((f: string) => f.endsWith('.plugin.yaml'))
  .forEach((file) => {
    const raw = load(readFileSync(join(pluginsDir, file), 'utf-8')) as RawPlugin;

    (['organization', 'project'] as const).forEach((section) => {
      (raw?.menu?.[section] ?? []).forEach((item) => {
        if (item?.icon) icons.add(item.icon);
      });
    });
  });

const sorted = [...icons].sort();

const lines = [
  '// AUTO-GENERATED by scripts/generate-plugin-icons.ts — run `just generate` to update.',
  'import {',
  ...sorted.map((n) => `  ${n},`),
  "} from '@ng-icons/tabler-icons';",
  '',
  'const pluginIcons: Record<string, string> = {',
  ...sorted.map((n) => `  ${n},`),
  '};',
  '',
  'export default pluginIcons;',
  '',
];

writeFileSync(outputFile, lines.join('\n'));
// eslint-disable-next-line no-console
console.log(`Generated ${icons.size} plugin icon(s): ${sorted.join(', ')}`);
