// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const tenantCreate = `-- name: TenantCreate :one
INSERT INTO organization.tenants (name)
VALUES ($1)
RETURNING id, name, created
`

func (q *Queries) TenantCreate(ctx context.Context, name string) (OrganizationTenant, error) {
	row := q.db.QueryRow(ctx, tenantCreate, name)
	var i OrganizationTenant
	err := row.Scan(&i.ID, &i.Name, &i.Created)
	return i, err
}

const userCreate = `-- name: UserCreate :one
INSERT INTO organization.users (tenant_id, name, external_id)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, name, external_id, created
`

type UserCreateParams struct {
	TenantID   uuid.UUID
	Name       string
	ExternalID string
}

func (q *Queries) UserCreate(ctx context.Context, arg UserCreateParams) (OrganizationUser, error) {
	row := q.db.QueryRow(ctx, userCreate, arg.TenantID, arg.Name, arg.ExternalID)
	var i OrganizationUser
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ExternalID,
		&i.Created,
	)
	return i, err
}

const userGetByExternalID = `-- name: UserGetByExternalID :one
SELECT id, tenant_id, name, external_id, created
FROM organization.users
WHERE external_id = $1
`

func (q *Queries) UserGetByExternalID(ctx context.Context, externalID string) (OrganizationUser, error) {
	row := q.db.QueryRow(ctx, userGetByExternalID, externalID)
	var i OrganizationUser
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ExternalID,
		&i.Created,
	)
	return i, err
}

const userGetByID = `-- name: UserGetByID :one
SELECT id, tenant_id, name, external_id, created
FROM organization.users
WHERE id = $1
`

func (q *Queries) UserGetByID(ctx context.Context, id uuid.UUID) (OrganizationUser, error) {
	row := q.db.QueryRow(ctx, userGetByID, id)
	var i OrganizationUser
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ExternalID,
		&i.Created,
	)
	return i, err
}

const userUpdate = `-- name: UserUpdate :one
UPDATE organization.users
SET name = $2
WHERE external_id = $1
RETURNING id, tenant_id, name, external_id, created
`

type UserUpdateParams struct {
	ExternalID string
	Name       string
}

func (q *Queries) UserUpdate(ctx context.Context, arg UserUpdateParams) (OrganizationUser, error) {
	row := q.db.QueryRow(ctx, userUpdate, arg.ExternalID, arg.Name)
	var i OrganizationUser
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ExternalID,
		&i.Created,
	)
	return i, err
}

const userUpsert = `-- name: UserUpsert :one
INSERT INTO organization.users (tenant_id, name, external_id)
VALUES ($1, $2, $3)
ON CONFLICT (external_id)
DO UPDATE SET name = EXCLUDED.name
RETURNING id, tenant_id, name, external_id, created
`

type UserUpsertParams struct {
	TenantID   uuid.UUID
	Name       string
	ExternalID string
}

func (q *Queries) UserUpsert(ctx context.Context, arg UserUpsertParams) (OrganizationUser, error) {
	row := q.db.QueryRow(ctx, userUpsert, arg.TenantID, arg.Name, arg.ExternalID)
	var i OrganizationUser
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ExternalID,
		&i.Created,
	)
	return i, err
}
