// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const tenantGetByID = `-- name: TenantGetByID :one
SELECT id, name, created
FROM organization.tenants
WHERE id = $1
`

func (q *Queries) TenantGetByID(ctx context.Context, id uuid.UUID) (OrganizationTenant, error) {
	row := q.db.QueryRow(ctx, tenantGetByID, id)
	var i OrganizationTenant
	err := row.Scan(&i.ID, &i.Name, &i.Created)
	return i, err
}

const tenantUpdate = `-- name: TenantUpdate :one
UPDATE organization.tenants
SET name = $2
WHERE id = $1
RETURNING id, name, created
`

type TenantUpdateParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) TenantUpdate(ctx context.Context, arg TenantUpdateParams) (OrganizationTenant, error) {
	row := q.db.QueryRow(ctx, tenantUpdate, arg.ID, arg.Name)
	var i OrganizationTenant
	err := row.Scan(&i.ID, &i.Name, &i.Created)
	return i, err
}
