root = "/src"
tmp_dir = "tmp"

[build]
cmd = "go build -o tmp/dcim-api ./dcim-api/cmd/dcim-api"
entrypoint = "tmp/dcim-api"
include_ext = ["go", "mod", "sum"]
include_dir = ["dcim-api"]
exclude_dir = ["tmp"]
delay = 500

[log]
time = false
