server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    add_header Content-Security-Policy "default-src 'self'; img-src 'self' data:; connect-src 'self' ${CONNECT_SRC}; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline';" always;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /assets/config/ {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }
}
