#!/usr/bin/env bash
# Hetzner Cloud one-time-use box — NO local nix required.
#
# Local deps: ssh, curl, and docker (you already run docker for fundament/k3d).
#   - hcloud CLI is fetched as a pinned static binary into cache/ (not brew/nix).
#   - NixOS is installed with nixos-anywhere run inside a throwaway `nixos/nix`
#     container, where root is a TRUSTED nix user by default. That is the missing
#     ingredient on a stock nix install (trusted-users=root only), and it lets
#     --build-on-remote work: the box builds the closure itself (native x86_64), the
#     container just orchestrates over SSH. Clean disko install — no infect.
#
# Runs on macOS or Linux. Usage: ./hetzner.sh {up|down|ssh|status}
set -euo pipefail
cd "$(dirname "$0")"

# --- config (override via env) ---------------------------------------------
HZ_TYPE=${HZ_TYPE:-cx53}              # 16 vCPU / 32GB / 320GB. cx43 (16GB) OOMs the full stack
                                     # (gardener runs several apiservers + fundament). ccx43=64GB if needed.
HZ_IMAGE=${HZ_IMAGE:-ubuntu-24.04}   # base image nixos-anywhere kexecs away from (any works)
HZ_LOCATION=${HZ_LOCATION:-nbg1}     # EU (CX is EU-only)
HZ_NAME=${HZ_NAME:-fundament-test}
HZ_KEYNAME=${HZ_KEYNAME:-fundament-admin}
BOX_USER=${BOX_USER:-fundament}      # login user on the box (must match modules/baseline.nix)
SSH_PORT=${SSH_PORT:-2022}           # NixOS sshd (baseline.nix); install phase is :22
HCLOUD_VERSION=${HCLOUD_VERSION:-1.51.0}
NIX_IMAGE=${NIX_IMAGE:-nixos/nix:latest}
ENVFILE=secrets/hetzner.env
CACHE=cache/bin
ADMIN_KEYS_NIX=cache/admin-keys.nix  # generated per-deploy: the box's authorized admin key(s)

# print a progress line to stdout
log() { printf '>> %s\n' "$*"; }
# print an error to stderr and abort
die() { printf '!! %s\n' "$*" >&2; exit 1; }

# Admin pubkey registered with hcloud for the install phase; prefer ed25519, else rsa.
if [ -z "${ADMIN_PUBKEY:-}" ]; then
  for k in "$HOME/.ssh/id_ed25519.pub" "$HOME/.ssh/id_rsa.pub"; do
    [ -f "$k" ] && { ADMIN_PUBKEY="$k"; break; }
  done
  ADMIN_PUBKEY=${ADMIN_PUBKEY:-$HOME/.ssh/id_ed25519.pub}   # for the not-found message
fi

# Materialize the box's authorized admin key into a nix file the flake imports, so the
# login key is the operator's own — never hardcoded. Source: admin_pubkey from the env
# file if set, else the resolved local pubkey file. Written before nixos-anywhere builds.
write_admin_keys() {
  local key
  if [ -n "${admin_pubkey:-}" ]; then
    key=$admin_pubkey                                  # explicit key from secrets/hetzner.env
  else
    [ -f "$ADMIN_PUBKEY" ] || die "admin pubkey not found: $ADMIN_PUBKEY (set admin_pubkey in $ENVFILE, ADMIN_PUBKEY=..., or create an ssh key)"
    key=$(cat "$ADMIN_PUBKEY")                         # fall back to the local pubkey we register with hcloud
  fi
  [ -n "$key" ] || die "empty admin pubkey"
  mkdir -p "$(dirname "$ADMIN_KEYS_NIX")"
  printf '# GENERATED by hetzner.sh — box admin SSH key(s). gitignored; do not commit.\n[\n  "%s"\n]\n' "$key" > "$ADMIN_KEYS_NIX"
}

# Cattle boxes reuse IPs across recreations, so never record/verify host keys.
SSH_OPTS=(-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR -o ConnectTimeout=8)

# --- token -----------------------------------------------------------------
[ -f "$ENVFILE" ] || die "missing $ENVFILE (api_key=...); cp $ENVFILE.example $ENVFILE"
set -a; . "$ENVFILE"; set +a
export HCLOUD_TOKEN="${api_key:?api_key not set in $ENVFILE}"

# --- helpers ---------------------------------------------------------------
# pinned static hcloud (no nix/brew)
ensure_hcloud() {
  HC="$CACHE/hcloud"
  if [ ! -x "$HC" ]; then
    mkdir -p "$CACHE"
    os=$(uname -s | tr '[:upper:]' '[:lower:]')
    arch=$(uname -m); case "$arch" in arm64|aarch64) arch=arm64;; x86_64|amd64) arch=amd64;; *) die "unsupported arch $arch";; esac
    url="https://github.com/hetznercloud/cli/releases/download/v${HCLOUD_VERSION}/hcloud-${os}-${arch}.tar.gz"
    log "fetching hcloud ${HCLOUD_VERSION} ($os/$arch)"
    curl -fsSL "$url" | tar -xz -C "$CACHE" hcloud || die "hcloud download failed: $url"
    chmod +x "$HC"
  fi
}
# run the fetched hcloud binary (token comes from the exported HCLOUD_TOKEN)
hc() { "$HC" "$@"; }

# public IPv4 of the box, or die (hcloud prints empty + exits 0 for a server with no IPv4).
box_ip() {
  local ip; ip=$(hc server ip "$HZ_NAME" 2>/dev/null) || die "no $HZ_NAME server — run ./hetzner.sh up"
  [ -n "$ip" ] || die "$HZ_NAME has no public IPv4"
  printf '%s\n' "$ip"
}

# poll SSH on host:port as the given user until it answers (tries x 8s); 0 if reachable
wait_ssh() { # host user tries port
  local i
  for i in $(seq 1 "${3:-60}"); do
    ssh -p "${4:-22}" "${SSH_OPTS[@]}" "${2}@${1}" true 2>/dev/null && return 0
    sleep 8
  done
  return 1
}

# Stage a SANITIZED copy of the flake source into a fresh temp dir and print its path.
# Only nix-relevant files go in — NOT secrets/ (Hetzner token) or the rest of cache/
# (private SSH keys, box CA key, machine-id). Critical because /work is mounted as a
# plain (non-git) path, so nix copies the WHOLE tree into the store and --build-on-remote
# ships it to the box; .gitignore does not filter a plain-path flake source. Only
# cache/admin-keys.nix is needed (modules/baseline.nix imports ../cache/admin-keys.nix).
stage_flake_src() {
  local dir; dir=$(mktemp -d "${TMPDIR:-/tmp}/fundament-flake.XXXXXX")
  cp flake.nix flake.lock "$dir/"
  cp -R hosts modules "$dir/"
  mkdir -p "$dir/cache"
  cp "$ADMIN_KEYS_NIX" "$dir/cache/admin-keys.nix"
  printf '%s\n' "$dir"
}

# --- install NixOS onto an already-created box -----------------------------
# Returns 0 only when the installed NixOS answers SSH on :$SSH_PORT (nixos-anywhere's
# exit code isn't reliable — it often drops SSH on the post-install reboot). Recovers
# the "installed but not cleanly rebooted" case with one hard reset.
deploy_once() { # ip priv
  local ip=$1 priv=$2
  log "$HZ_NAME @ $ip — waiting for SSH on :22"
  wait_ssh "$ip" root 60 22 || { log "box never reachable on :22"; return 1; }

  local src; src=$(stage_flake_src)
  trap 'rm -rf "$src"' RETURN
  log "installing NixOS via nixos-anywhere (throwaway nixos/nix container; build-on-remote)"
  docker run --rm \
    -v "$src:/work" -w /work \
    -v "$priv:/root/.ssh/id_rsa:ro" \
    -e NIX_CONFIG="experimental-features = nix-command flakes" \
    "$NIX_IMAGE" \
    nix run github:nix-community/nixos-anywhere -- \
      --flake /work#hetzner --build-on-remote \
      -i /root/.ssh/id_rsa \
      --ssh-option StrictHostKeyChecking=no --ssh-option UserKnownHostsFile=/dev/null \
      "root@$ip" \
    || log "nixos-anywhere exited nonzero (usually just the post-install reboot dropping SSH) — verifying over SSH"

  log "waiting for the installed NixOS on :$SSH_PORT"
  wait_ssh "$ip" "$BOX_USER" 40 "$SSH_PORT" && return 0
  log "no SSH on :$SSH_PORT yet — hard-resetting to boot from the installed disk"
  hc server reset "$HZ_NAME" >/dev/null 2>&1 || true
  wait_ssh "$ip" "$BOX_USER" 45 "$SSH_PORT" && return 0
  return 1
}

# create the box (if absent) and install NixOS onto it; on failure, destroy + recreate (HZ_RETRIES)
cmd_up() {
  ensure_hcloud
  command -v docker >/dev/null 2>&1 || die "docker is required (used to run nixos-anywhere without local nix)"
  docker info >/dev/null 2>&1 || die "docker daemon is not running"
  [ -f "$ADMIN_PUBKEY" ] || die "admin pubkey not found: $ADMIN_PUBKEY (set ADMIN_PUBKEY=..., or create an ssh key)"
  local priv="${ADMIN_PUBKEY%.pub}"
  [ -f "$priv" ] || die "private key not found: $priv (matching $ADMIN_PUBKEY)"
  # Bake the operator's admin key into the flake (cache/admin-keys.nix) before installing.
  write_admin_keys
  hc ssh-key describe "$HZ_KEYNAME" >/dev/null 2>&1 \
    || hc ssh-key create --name "$HZ_KEYNAME" --public-key-from-file "$ADMIN_PUBKEY"

  # Cattle: recover cheaply if we can, else start fresh (destroy + recreate). HZ_RETRIES total attempts.
  local tries=${HZ_RETRIES:-2} n=0 ip
  while :; do
    n=$((n + 1))
    if ! hc server describe "$HZ_NAME" >/dev/null 2>&1; then
      log "creating $HZ_NAME ($HZ_TYPE @ $HZ_LOCATION) — BILLING STARTS"
      hc server create --name "$HZ_NAME" --type "$HZ_TYPE" --image "$HZ_IMAGE" \
        --location "$HZ_LOCATION" --ssh-key "$HZ_KEYNAME" \
        || die "server create failed (on resource_unavailable try another HZ_LOCATION, e.g. hel1/fsn1)"
    else
      log "$HZ_NAME already exists; reusing"
    fi
    ip=$(box_ip)
    if deploy_once "$ip" "$priv"; then
      log "READY:  ssh -p $SSH_PORT $BOX_USER@$ip   (or: ./hetzner.sh ssh)"
      log "BILLING IS RUNNING — tear down with: ./hetzner.sh down"
      return 0
    fi
    [ "$n" -ge "$tries" ] && die "deploy failed after $n attempt(s). Inspect with ./hetzner.sh ssh, or ./hetzner.sh down."
    log "attempt $n failed — starting fresh (destroying $HZ_NAME and recreating)"
    hc server delete "$HZ_NAME" >/dev/null 2>&1 || true
    sleep 5
  done
}

# destroy the box (stops billing)
cmd_down() {
  ensure_hcloud
  hc server delete "$HZ_NAME" && log "deleted $HZ_NAME — billing stopped."
}
# list the project's servers (so a billing box is never forgotten)
cmd_status() { ensure_hcloud; hc server list; }
# open an interactive shell on the box (NixOS, port 2022)
cmd_ssh()    { ensure_hcloud; exec ssh -p "$SSH_PORT" "${SSH_OPTS[@]}" "$BOX_USER@$(box_ip)"; }

case "${1:-}" in
  up) cmd_up ;;
  down) cmd_down ;;
  ssh) cmd_ssh ;;
  status) cmd_status ;;
  *) die "usage: $0 {up|down|ssh|status}" ;;
esac
